server:
  port: 8888
  servlet:
    context-path: /res

# 静态资源访问前缀
spring:
#  mvc:
#    static-path-pattern: /res/**

  # 自定义静态资源访问路径
  web:
    resources:
      static-locations: classpath:/lyw/
      add-mappings: false