spring:
  redis:
    host: '192.168.169.5'
    port: 6382
    password: root
    database: 0
    client-type: lettuce
    jedis:
      pool:
        max-active: 10  # 最大活跃
        min-idle: 5     # 最小空闲