spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bjpowernode?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '1870168452'
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123


# 排除这些资源
      web-stat-filter:
        exclusions: '*.js,*.css,*.jpg,*.png,*.gif,*.ico,/druid/*'
        enabled: true
        url-pattern: /*
      aop-patterns: com.lyw

# 开启监控功能
      filter:
        stat:
          enabled: true
# 日志是否记录慢查询语句
          log-slow-sql: true
# 超过1s的语句成为慢查询
          slow-sql-millis: 1000

# 开启web，url监控功能
        wall:
          enabled: true
# 不允许删除表
          config:
            drop-table-allow: false